### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by thecalle** [lemariva/N-Queens-Problem#1]
Starting with example parameters, stops test. Rasbian

_~/rPI-Tests/scripts $ python queenpool_multithread.py multithread_output.csv 12 4 100
Calculating loop number 1 (of 100)
Starting calculation
Traceback (most recent call last):
  File "queenpool_multithread.py", line 118, in <module>
    main(sys.argv)
  File "queenpool_multithread.py", line 107, in main
    seconds, microseconds, solutions = nqueen_obj.solve()
  File "queenpool_multithread.py", line 31, in solve
    self._solutions = pool.map(self.nqueens, range(self._nthreads))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed_

**Comment by lemariva** [comment]
Hi there, it works only with Python 3.x
